---
title: "Global Figures"
output: html_notebook
---

```{r}
library(tidyverse)
library(stringr)
library(Seurat)
```

```{r}
load("~/maca/save/All_seurat_tiss.Robj")
```

Loading annotations
```{r}
anno_plate = read_csv('~/maca/metadata/maca_3month_combined_cell_annotations.csv')
anno_plate <- rename(anno_plate, cell = X1)
anno_plate <- rename(anno_plate, anno_tissue = tissue)
anno_plate %>% group_by(anno_tissue, annotation, subannotation) %>% summarize(count = n())

anno_tenx = read_csv('~/maca/metadata/maca_3month_combined_cell_annotations_10x.csv')
anno_tenx <- rename(anno_tenx, cell = X1)
anno_tenx <- rename(anno_tenx, anno_tissue = tissue)
anno_tenx %>% group_by(anno_tissue, annotation, subannotation) %>% summarize(count = n())
```

```{r}
tissue_colors <- read_csv('~/maca/metadata/tissue_colors.csv')
tissue_colors <- rename(tissue_colors, anno_tissue = X1)
tissue_colors
```

```{r}
df <- as_tibble(tiss@meta.data)
df <- df %>% select(-(annotation:subannotation))
df <- rownames_to_column(df, var = "cell")
df <- left_join(df, anno_plate, by = 'cell')

df['tSNE_1'] <- tiss@dr$tsne@cell.embeddings[,'tSNE_1']
df['tSNE_2'] <- tiss@dr$tsne@cell.embeddings[,'tSNE_2']
df['cluster'] <- tiss@ident
df <- left_join(df, tissue_colors, by='anno_tissue')
```


```{r, fig.width = 8, fig.height = 6}
df %>% ggplot(aes(x = tSNE_1, y = tSNE_2)) + geom_point(aes(color = color), size=0.1) +
   scale_color_identity(breaks = tissue_colors$color, 
                        labels = tissue_colors$anno_tissue, 
                        guide = "legend") + 
  guides(colour = guide_legend(override.aes = list(size=2)))

ggsave('figures/tsne_by_tissue_plates.pdf', width = 104, height = 55, units = "mm")
```


```{r}
repeated_annotations <- anno %>% group_by(annotation, anno_tissue) %>% summarize(count = n()) %>% ungroup() %>% group_by(annotation) %>% summarize(count = n()) %>% filter(count > 1) %>% pull(annotation)
repeated_annotations
```



# TenX TSNE

```{r}
load('~/maca/save/10x_All_regressed_seurat_tiss.Robj')
```

```{r}
dfX <- as_tibble(tissX@meta.data)
dfX <- dfX %>% select(-(annotation:subannotation))

#dfX <- rownames_to_column(dfX, var = "cell")

dfX <- mutate(dfX, tissue = fct_recode(tissue,
    "Mammary_Gland" = "Mammary"))

dfX['tSNE_1'] <- tissX@dr$tsne@cell.embeddings[,'tSNE_1']
dfX['tSNE_2'] <- tissX@dr$tsne@cell.embeddings[,'tSNE_2']

dfX <- left_join(dfX, anno_tenx, by = 'cell')

dfX['anno_tissue'] <- dfX['tissue']
dfX['cluster'] <- tissX@ident

dfX <- left_join(dfX, tissue_colors, by='anno_tissue')
```

```{r, fig.width = 8, fid.height = 6}
dfX %>% ggplot(aes(x = tSNE_1, y = tSNE_2)) + geom_point(aes(color = color), size=0.1) +
   scale_color_identity(breaks = tissue_colors$color, 
                        labels = tissue_colors$anno_tissue, 
                        guide = "legend") + 
  guides(colour = guide_legend(override.aes = list(size=2)))

ggsave('figures/tsne_by_tissue_tenx.pdf', width = 104, height = 55, units = "mm")
```

# Heatmaps for big clustering

```{r}
df <- drop_na(df, annotation)
df <- df %>% mutate(anno_and_tissue = paste(annotation, anno_tissue, sep='-'),
              anno_and_sub = paste(annotation, subannotation, sep='-'),)
```

```{r}
save(df, file = 'save/annotation_dataframe.Robj')
```


Do we see mixing of tissues and cell types in the top-level clustering?


```{r, fig.width = 15, fig.height = 40}
hmap_df <- df %>% drop_na(anno_and_tissue) %>% group_by(anno_and_tissue, cluster) %>% summarize(count = n()) %>% filter(count > 5) %>% spread(key=cluster, value = count, fill = 0)
hmap_mat <- as.data.frame(hmap_df %>% ungroup() %>% select(-anno_and_tissue))
row.names(hmap_mat) <- hmap_df$anno_and_tissue

#heatmaply(as.matrix(log10(hmap_mat+1)), distfun = 'pearson', width = 700, height = 1000, plot_method = 'ggplot')
gplots::heatmap.2(as.matrix(log10(hmap_mat+1)), col = viridis(100), trace = "none", margins=c(0,36), Colv=FALSE, dendrogram = "row", cexRow = 2.0, cexCol = 2.0, key = FALSE, keysize = 0.05, RowSideColors = )
```

## Heatmap for tenx

```{r}
dfX <- drop_na(dfX, annotation)
dfX <- dfX %>% mutate(anno_and_tissue = paste(annotation, anno_tissue, sep='-'),
              anno_and_sub = paste(annotation, subannotation, sep='-'))
```

```{r, fig.width = 15, fig.height = 40}
hmap_dfX <- dfX %>% drop_na(anno_and_tissue) %>% group_by(anno_and_tissue, cluster) %>% summarize(count = n()) %>% filter(count > 5) %>% spread(key=cluster, value = count, fill = 0)
hmap_matX <- as.data.frame(hmap_dfX %>% ungroup() %>% select(-anno_and_tissue))
row.names(hmap_matX) <- hmap_dfX$anno_and_tissue

#heatmaply(as.matrix(log10(hmap_mat+1)), distfun = 'pearson', width = 700, height = 1000, plot_method = 'ggplot')
gplots::heatmap.2(as.matrix(log10(hmap_matX+1)), col = viridis(100), trace = "none", margins=c(0,36), Colv=FALSE, dendrogram = "row", cexRow = 2.0, cexCol = 2.0, key = FALSE, keysize = 0.05)
```

