---
title: "MACA Notebook"
output: html_notebook
---

```{r}
rootdir = "~/code/maca/"
```


```{r}
library(Seurat)
library(dplyr)
library(Matrix)
```

Load the plate metadata.

```{r}
metadata <- read.csv(file = paste0(rootdir, "metadata/MACA_Metadata.csv"), sep=",", header = TRUE)
colnames(metadata)[1] <- "plate.barcode"
head(metadata)
```

Check for available files.
```{r}
 count_files = list.files(paste0(rootdir, "data/"), pattern = "*counts.tab",recursive = TRUE)
 metadata_files = list.files(paste0(rootdir, "data/"), pattern = "*metadata.tab",recursive = TRUE)

 downloaded_plates = lapply(count_files, function(x) strsplit(x,"[./]")[[1]][1])

 metadata = metadata[metadata$plate.barcode %in% downloaded_plates,]
 head(metadata)
```

```{r}
tissue_plates = filter(metadata, tissue == "Pancreas" & mouse.age ==3)[,c('plate.barcode','tissue','subtissue','mouse.sex')]
tissue_counts = paste0(tissue_plates$plate.barcode, '.counts.tab')

remove_erccs = function(counts){
  erccs <- grep(pattern = "^ERCC-", x = rownames(x = counts), value = TRUE)
  percent.ercc <- Matrix::colSums(counts[erccs, ])/Matrix::colSums(counts)
  ercc.index <- grep(pattern = "^ERCC-", x = rownames(x = counts), value = FALSE)
  counts <- counts[-ercc.index,]
}

raw.data = read.csv(file = paste0(rootdir,"data/", tissue_counts[1]) ,sep='\t')
data.no.erccs = remove_erccs(raw.data)

tiss <- CreateSeuratObject(raw.data = data.no.erccs, project = "Pancreas", 
                    min.cells = 5, min.genes = 5)

for (file in count_files[2:length(tissue_counts)]){
  raw.data = read.csv(file = paste0(rootdir,"data/", file), sep='\t')
  data.no.erccs = remove_erccs(raw.data)
  tiss <- AddSamples(object = tiss, new.data = data.no.erccs, 
                     add.cell.id = file, do.normalize = FALSE,min.cells = 5, min.genes = 5)
}
```


# ```{r}
# for (plate in filter(metadata, tissue == "Pancreas" & mouse.age == 3)$plate.barcode){
#   raw.data <- read.
#   liver <- CreateSeuratObject(raw.data = liver_P7_0.data, project = "liver", 
#                     min.cells = 5, min.genes = 5)
#   print(plate)
# }
# ```


# ```{r}
# raw.data <- read.csv(file = "~/Downloads/MAA000574/MAA000574.counts.tab",sep='\t')
# ```



# ```{r}
# tiss <- CreateSeuratObject(raw.data = raw.data, project = "pancreas", 
#                     min.cells = 5, min.genes = 5)
# ```

Calculate percent ribosomal genes and set genes to ignore, like highly-abundant lincRNAs Malat1 and Rn45s.

```{r}
ribo.genes <- grep(pattern = "^Rp[sl][[:digit:]]", x = rownames(x = tiss@data), value = TRUE)

percent.ribo <- Matrix::colSums(tiss@raw.data[ribo.genes, ])/Matrix::colSums(tiss@raw.data)

tiss <- AddMetaData(object = tiss, metadata = percent.ribo, col.name = "percent.ribo")

exclude.genes = c(ribo.genes,"Malat1","Rn45s")
```


```{r}
tiss <- NormalizeData(object = tiss)
tiss <- ScaleData(object = tiss)
tiss <- FindVariableGenes(object = tiss, do.plot = TRUE)
```



# ```{r}
# tiss <- NormalizeData(object = tiss, normalization.method = "LogNormalize",
#     scale.factor = 10000)
# tiss <- ScaleData(object = tiss, vars.to.regress = c("nUMI", "percent.ribo"))
# tiss <- FindVariableGenes(object = tiss, do.plot = TRUE)
# ```
Run Principal Component Analysis.
```{r}
tiss <- RunPCA(object = tiss, pc.genes = tiss@var.genes, do.print = TRUE, pcs.print = 1:5, 
    genes.print = 5)
```

```{r}
tiss <- ProjectPCA(object = tiss, do.print = FALSE)
```


```{r, echo=FALSE, fig.height=4, fig.width=8}
PCHeatmap(object = tiss, pc.use = 1:3, cells.use = 500, do.balanced = TRUE, label.columns = FALSE)
```

```{r}
PCElbowPlot(object = tiss)
```


```{r}
tiss <- FindClusters(object = tiss, reduction.type = "pca", dims.use = 1:20, 
    resolution = 1.0, print.output = 0, save.SNN = TRUE)
```


```{r}
tiss <- RunTSNE(object = tiss, dims.use = 1:20, seed.use = 10)
```

```{r}
# note that you can set do.label=T to help label individual clusters
TSNEPlot(object = tiss)
```

```{r}
tiss.markers <- FindAllMarkers(object = tiss, only.pos = TRUE, min.pct = 0.25, 
    thresh.use = 0.25)
tiss.markers %>% group_by(cluster) %>% top_n(4, avg_diff)
```
```{r}
genes_to_check = c('Ins1', 'Ins2', 'Gcg')

FeaturePlot(tiss, genes_to_check, pt.size = 1)
```


```{r}
vlnPlot(tiss, genes_to_check)
```


```{r}
# Get markers for a particular cluster
cluster0_markers = filter(tiss.markers, cluster == 0)$gene

DotPlot(tiss, genes.plot = cluster0_markers[1:10])
```


```{r}
tiss = BuildClusterTree(tiss)
# DOn't need the next line because BuildClusterTree makes the plot already
# PlotClusterTree(tiss)
```


```{r}
# Get markers for a particular cluster
cluster0_markers = filter(tiss.markers, cluster == 0)$gene

DotPlot(tiss, genes.plot = cluster0_markers[1:10], group.by = 'cluster')
```
