---
title: "10x vs Plate"
output: html_notebook
---

```{r}
#install.packages("tidyverse")
library(tidyverse)
library(stringr)
library(Seurat)

Sys.setenv(R_MAX_NUM_DLLS=150)
```


```{r}
load("~/maca/save/All_seurat_tiss.Robj")
load("~/maca/save/10x_All_seurat_tiss.Robj")

tiss@meta.data['cell'] <- rownames(tiss@meta.data)
tissX@meta.data['cell'] <- rownames(tissX@meta.data)

```

Add in percent Rn54s.
```{r}
percent.Rn45s <- Matrix::colSums(tiss@raw.data[c('Rn45s'), ])/Matrix::colSums(tiss@raw.data)
tiss <- AddMetaData(object = tiss, metadata = percent.Rn45s, col.name = "percent.Rn45s")

percent.Rn45s <- tissX@raw.data[c('Rn45s'), ]/Matrix::colSums(tissX@raw.data)
tissX <- AddMetaData(object = tissX, metadata = percent.Rn45s, col.name = "percent.Rn45s")
```

Extract just the metadata from plates and tenx cells.
```{r}
just_plates = as_tibble(tiss@meta.data[c('tissue', 'subtissue', 'percent.ribo', 'percent.Rn45s','nGene', 'plate.barcode')])
just_plates <- rownames_to_column(just_plates, "cell")
just_plates['method'] <- 'plate'
just_plates <- rename(just_plates, run = plate.barcode)

just_tenx = as_tibble(tissX@meta.data[c('tissue', 'percent.ribo', 'nGene','channel', 'percent.Rn45s')])
just_tenx <- rownames_to_column(just_tenx, "cell")
just_tenx['method'] <- '10x'
just_tenx <- rename(just_tenx, run = channel)

df <- bind_rows(just_plates, just_tenx)
```

```{r}
df <- df %>% mutate(tissue = fct_recode(tissue,
    "Mammary" = "Mammary_Gland"))
df %>% count(tissue)
```


```{r}
common_tissues <- c("Bladder", "Heart", "Kidney", "Liver","Lung","Mammary","Marrow","Muscle",
                         "Spleen", "Tongue", "Thymus")
```


How do the number of genes detected vary across tissues and methods?

```{r, fig.width = 8, fig.height = 20}
filter(df, tissue %in% common_tissues) %>% ggplot(aes(nGene, ..density..,colour = method)) + 
  geom_freqpoly(binwidth = 300) +
  facet_wrap(~ tissue, nrow = 8, scales = "free_x")
```

Is this an artifact of the channel used?

```{r}
medians <- df %>% group_by(method, tissue, run) %>% summarize(median_genes = median(nGene), n_cells = n()) 
```

```{r}
medians %>% filter(method == '10x') %>% ggplot(aes(x = median_genes, y = n_cells, color = tissue)) + geom_point()  +
    scale_color_brewer(palette="Spectral")
```


How about percent ribo?


```{r, fig.width = 8, fig.height = 20}
filter(df, tissue %in% common_tissues) %>% ggplot(aes(percent.ribo, ..density..,colour = method)) + 
  geom_freqpoly(binwidth = 0.01) +
  facet_wrap(~ tissue, nrow = 8, scales = "free_x")
```


What about Rn45s? It's dramatically different between 10X and plateseq.

```{r}
median_Rn45s <- df %>% group_by(method, tissue, run) %>% summarize(median_Rn45s = median(percent.Rn45s), 
                                                                   median_ribo = median(percent.ribo),
                                                                   n_cells = n()) 
```

```{r}
median_Rn45s %>% filter(tissue %in% common_tissues,) %>% ggplot(aes(x = median_Rn45s, y = median_ribo, color = tissue, shape = method)) + geom_point()  +
    scale_color_brewer(palette="Spectral")
```

```{r, fig.width = 8, fig.height = 20}
filter(df, tissue %in% common_tissues, method == 'plate') %>% ggplot(aes(percent.Rn45s,..density..,colour = tissue)) + 
  geom_freqpoly(binwidth = 0.01) +
  facet_wrap(~ tissue, nrow = 8, scales = "free_x")
```

# Dynamic Range

Get a few cells from each method with values in a certain range.
```{r}
subset.size <- 2

cell.subset <- filter(df, tissue == 'Heart', nGene > 2900, nGene < 3100) %>% 
    group_by(method) %>% 
    sample_n(subset.size) %>%
    pull(cell)
```

```{r, fig.width = 4, fig.height = 8}
par(mfrow=c(2,1))

expr <- tissX@data[,cell.subset[1]]
expr <- expr[expr > 0]
plot(sort(expr), ylab = "log expression", xlab = "gene index", col = "red")
title(main = "Heart 10x cell")

expr <- tiss@data[,cell.subset[3]]
expr <- expr[expr > 0]
plot(sort(expr), ylab = "log expression", xlab = "gene index", col = "green")
title(main = "Heart plateseq cell")
```


```{r, fig.width = 4, fig.height = 8}
par(mfrow=c(2,1))

expr <- tissX@raw.data[,cell.subset[1]]
expr <- expr[expr > 0]
plot(sort(expr), ylab = "expression", xlab = "gene index", col = "red", log = 'y')
title(main = "Heart 10x cell")

expr <- tiss@raw.data[,cell.subset[3]]
expr <- expr[expr > 0]
plot(sort(expr), ylab = "expression", xlab = "gene index", col = "green", log = 'y')
title(main = "Heart plateseq cell")
```


# Average Cells

```{r}
plates_marrow_meta = filter(tiss@meta.data, tissue == "Marrow")
tenx_marrow_meta = filter(tissX@meta.data, tissue == "Marrow")
```



